### ISSUE TITLE
Feature Request: Focus Far Manager Window After Executing a Command

### ISSUE THREAD

**Issue by larsborn** [huettenhain/frc#1]
I use Everything and `client.exe` to open directories in Far. Since I use a global shortcut to open the Everything search, Far was not necessarily the previously focused window. Could the plugin get the current Far window (through `GetConsoleWindow` for example) and focus that window after executing a command?

**Comment by huettenhain** [comment]
This is implemented in fb528e72772a18eb104a9d7217640a005f7e5877 and published as [v2.1](https://github.com/huettenhain/frc/releases/tag/V2.1).

**Comment by larsborn** [comment]
Awesome, thanks! Works like a charm 🎉
