### ISSUE TITLE
Behavior of Open Path in case of using FRC

### ISSUE THREAD

**Issue by joye-ramone** [huettenhain/frc#2]
Greeting,

As of now, when I use FRC with Everything search tool, both commands (Open Path and Open (Folders)) will work the same way for folder type of elements - open it. 

But it would be nice if FRC provide a separate command to always _Open Path_ of element no matter it is type - for file just open it parent folder and put selection on it and same for folder - open it parent folder and put selection on it. Actually, for files it is already working like this.

Examples: 
1. file c:\folder\file.txt
Open Path - open folder c:\folder and put selection at file.txt - that already work as expected

2. folder c:\folder\folder123 - that is what I am looking at
Open Path - open folder c:\folder\ and put selection at folder123  - **that is what I am looking for.**
And Open (Folders) - just open target folder c:\folder\folder123 - as it works right now.

**Comment by huettenhain** [comment]
Hey there and sorry for the delay! I see what you are saying, you want one option for it to behave just like `goto:` in FAR, which will also behave exactly like what you describe. That is no problem to do, I will get on it as soon as possible.

**Comment by huettenhain** [comment]
This is implemented in 654e044cda0d5e4f4615a6e15a0569dedb3ed441 and available in the [newly released version 2.2](https://github.com/huettenhain/frc/releases/tag/V2.2). It works like this:
- `GOTO` now does what _you_ requested, i.e. it always navigates to the parent directory and moves the cursor.
- `INTO` now implements the old behavior of `GOTO` where it will navigate into directories.

**Comment by joye-ramone** [comment]
Perfect! Thank you once again for this nice idea of this plugin.
