### ISSUE TITLE
Far as admin

### ISSUE THREAD

**Issue by pasha-zzz** [huettenhain/frc#3]
If Far running as admin and program (f.e. Everything) as user, client.exe shows error "Unable to open Mailslot handle."

**Comment by huettenhain** [comment]
Sounds like a permissions issue; I will look into it soon.

**Comment by huettenhain** [comment]
The question is: _Should_ someone be able to remote control the FAR instance of another user? I am a little undecided on this. Could you maybe motivate a little more why you can't run Everything and FAR as the same user?

**Comment by huettenhain** [comment]
I thought about it a little more and I think this is fine. FRC does not really let you do enough for this to be a giant security risk. I added the code to create the mailslot without any permission restrictions so you can now trigger the plugin inside an elevated process by using the client as a user.

**Comment by huettenhain** [comment]
Fixed in [V2.3](https://github.com/huettenhain/frc/releases/tag/V2.3). I will release this on the plugring ASAP.
