### ISSUE TITLE
Incorrect version info

### ISSUE THREAD

**Issue by pasha-zzz** [huettenhain/frc#6]
Plugin says to Far version 1.0.0.0 (RC) but 2.2 installed. And Renewal plugin always says update is available...
![image](https://github.com/huettenhain/frc/assets/8224786/ea20287f-8d82-429d-83fe-a726f30c719f)

**Comment by pasha-zzz** [comment]
Made PR with correction

**Comment by huettenhain** [comment]
PR #7 merged, will close this one out!
