### ISSUE TITLE
Mailslots are deprecated

### ISSUE THREAD

**Issue by montoner0** [huettenhain/frc#8]
Just a note that mailslots are [considered deprecated since Windows 11](https://techcommunity.microsoft.com/t5/storage-at-microsoft/the-beginning-of-the-end-of-remote-mailslots-as-part-of-windows/ba-p/3762048) so it's not far away the day when this plugin won't work on new Windows versions.

**Comment by huettenhain** [comment]
The way I read this is that only _remote_ mailslots are being deprecated, not the local ones I am using for FRC. Honestly, based on past experience with how Microsoft handles backwards compatibility in the Win32 API, this is _never_ going to go away entirely. That said, should local mailslots be impacted in the future (which I could not find any evidence of), I can easily replace it with a named pipe. For now, however, I will close this issue a I am working under the assumption that the mailslot API is not actually being deprecated.
